config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'resource_time_slot/:name' , to: 'bookings#resource_time_slot', as: :timeslots
  get 'booking_date_slots/:resource/date_of_booking=:date_of_booking', to: 'bookings#booking_date_slots', as: :date_slots
  namespace :admin do 
    get 'dashbord' => 'employees#dashbord'
    post 'change_status' => 'employees#change_status'
    resources :employees,:resources, :roles
  end
  resources :bookings, :employees, :complaints, :company
  devise_for :employees, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }, controllers: {
        confirmations: 'employees/confirmations'
      }

      as :employee do
      patch '/employee/confirmation' => 'employees/confirmations#update', :via => :patch, :as => :update_employee_confirmation
  end
  root "employees#entry"
  

end

app/models/employee.rb
#
# Class Employee provides functionality for managing employees related to company
#
# @author Amrut Jadhav  amrut@amuratech.com
#
class Employee 
  include Mongoid::Document
  include Mongoid::Timestamps
  #
  # @!attribute [rw] skip_password_validation
  #   @return [Boolean] whether to skip password validation or not
  attr_accessor :skip_password_validation
  #
  # @!attribute [rw] skip_validation
  #   @return [Boolean] Whether to skip validation or not 
  attr_accessor :skip_validation

  # Associations
	belongs_to :role
	belongs_to :company
	has_many :bookings, dependent: :destroy
	has_many :complaints, dependent: :destroy
  has_many :subordinates, class_name: "Employee", :inverse_of => :manager
  belongs_to :manager, class_name: "Employee", :inverse_of => :subordinates
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,   message: "email format" },
                       uniqueness:{scope: :company_id, message: "Email should be unique across the company"}
  validates :name, :email,:age, :role_id, :date_of_joining, presence: true
  validates :manager_id, presence: true, unless: :skip_validation
  #validates :role_id, :manager_id, :age, numericality: { only_integer: true, less_than: 2147483647, greater_than_or_equal_to: 1}, unless: :skip_validation
  validates :password, :password_confirmation, presence: {:message => 'no password'}, unless: :skip_password_validation

  # Callbacks
  before_save :lower_email

  # Devise options
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable, :confirmable






  field :name, type: String
  field :age, type: Integer
  field :date_of_joining, type: Date
  field :manager_id, type: BSON::ObjectId
  field :role_id, type: BSON::ObjectId
  field :company_id, type: BSON::ObjectId 
  field :email, type: String
## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  # Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable


  scope :employees, -> id { where(company_id:id) }
  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end

  #
  # Check whther password is required or not
  #
  #
  # @return [Boolean] Whether password is required or not
  # 
  def password_required?
    super if confirmed?
  end

  #
  # Checks whether password and password_confirmation match?
  #
  #
  # @return [Boolean] Whether fields match or not
  # 
  def password_match?
    self.password == self.password_confirmation
  end
 
  #
  # Function to check whether password has been set or not
  #
  #
  # @return [Boolean] Whether the encrypted_password field is blank or not
  # 
  def has_no_password?
    self.encrypted_password.blank?
  end

  # Devise::Models:unless_confirmed` method doesn't exist in Devise 2.0.0 anymore. 
  # Instead you should use `pending_any_confirmation`.  
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end
  def manager
    Employee.find(self.manager_id)
  end
  # def subordinates
  #   byebug
  #   e = Employee.where(manager_id:self.id)
  # end
  private

  #
  # Downcase the email and name of employee
  #
  #
  # @return [void] Downcase the fields
  # 
  def lower_email
   self.email.downcase!
   self.name.downcase!
  end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
	before_action :find_company
	before_action :find_another_employee, only: [:show,:edit, :update]
	before_action :find_complaints, only: [ :dashbord, :change_status]

	def index
		@employees = @company.employees
	end
	def new
		@employee = Employee.new
	end

	def create
		@employee = @company.employees.build(employee_params)
		@employee.skip_password_validation = true
		if @employee.save

			redirect_to admin_employees_path
		else
			render :new
		end
	end 

	def show
		redirect_to admin_employees_path
	end

	def edit;	end
	
	def update 
		@employee.skip_password_validation = true
			if @employee.update_attributes(employee_params)
				redirect_to admin_employees_path
			else
				render :edit
			end
	end

	def destroy
		@admin = @company.employees.find_by(name:"admin")
		#ClassName.delete_all(conditions: { _id: BSON::ObjectId("whatevertheidis")})
		if @company.employees.where(_id: params[:id]).destroy
			flash[:success] = "Employee and his bookings and complaints are succeesfully deleted"
			@company.employees.snapshot().where(manager_id:params[:id]).each do | record_emp |
				record_emp.manager_id = @admin.id
				record_emp.skip_password_validation = true
				record_emp.save
			end
		else
			flash[:danger] = "Error while deleting employee"
		end
		redirect_to admin_employees_path
	end
	
	def dashbord
		if @company.resources.any?
			@bookings = @company.bookings.where(status:0).where(:date_of_booking.gte => Date.today) if @company.bookings
			@complaints = @complaints.where(status:0) if @complaints
		end
	end

	def change_status
		if(params[:status])	
			flag = 0	
			booking = @company.bookings.find(params[:status][:booking_id])
			if params[:commit] =="Grant"
				booking.status = 1
			elsif params[:commit] == "Reject"
				flag = 1
				booking.status = 2
			end
			if flag == 1
				booking.save(validate:false)
			elsif !booking.save
				flash[:alert] = "#{booking.errors.full_messages}"
			end
			redirect_to :admin_dashbord
		end
		if(params[:status_complaint])
			complaint = @complaints.find(params[:status_complaint][:complaint_id])
			if params[:commit] == "Solve"
				complaint.status = 1
			end
			if complaint.save
			redirect_to :admin_dashbord
		end
		end
		
	end
	private
	
	def employee_params
		params.require(:employee).permit(:name, :email,:age, :date_of_joining, :role_id, :manager_id)
	end
	
	def find_complaints
		@complaints = @company.complaints
	end
	
	def find_another_employee
		@employee = @company.employees.find(params[:id])
	end
end

app/controllers/employees/confirmations_controller.rb
class Employees::ConfirmationsController < Devise::ConfirmationsController
  # Remove the first skip_before_filter (:require_no_authentication) if you
  # don't want to enable logged users to access the confirmation page.
  skip_before_filter :require_no_authentication
  skip_before_filter :authenticate_employee!
  before_action :check, only: [:update]

  def check

    flag = 0
    if (params[:employee][:password].empty?)
        flash[:danger] = "password can not be blank"
        flag = 1
    elsif (params[:employee][:password] != params[:employee][:password_confirmation])
        flash[:danger] = "password and password_confirmation should match"
        flag = 1
    elsif (params[:employee][:password].length < 6)
        flash[:danger] = "password length should be atleast 6"
        flag = 1
    end
    if flag == 1
      redirect_to :back, params
    end 
  end 



  # PUT /resource/confirmation
  def update
    with_unconfirmed_confirmable do
      if @confirmable.has_no_password?
        @confirmable.attempt_set_password(params[:employee])
        if @confirmable.valid? and @confirmable.password_match?
          do_confirm
        else
          do_show
          @confirmable.errors.clear #so that we wont render :new
        end
      else
        @confirmable.errors.add(:email, :password_already_set)
      end
    end

    if !@confirmable.errors.empty?
      self.resource = @confirmable
      render 'devise/confirmations/new' #Change this if you don't have the views on default path
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    with_unconfirmed_confirmable do
      if @confirmable.has_no_password?
        do_show
      else
        do_confirm
      end
    end
    unless @confirmable.errors.empty?
      self.resource = @confirmable
      render 'devise/confirmations/new' #Change this if you don't have the views on default path 
    end
  end

  protected

  def with_unconfirmed_confirmable
    original_token = params[:confirmation_token]
    @confirmation_token = params[:confirmation_token]
    #confirmation_token = Devise.token_generator.digest(Employee, :confirmation_token, original_token)
    @confirmable = Employee.find_or_initialize_with_error_by(:confirmation_token, @confirmation_token)
    if !@confirmable.new_record?
      @confirmable.only_if_unconfirmed {yield}
    end
  end

  def do_show
    original_token = params[:confirmation_token]
    @confirmation_token = params[:confirmation_token]
   # confirmation_token = Devise.token_generator.digest(Employee, :confirmation_token, original_token)
    @confirmable = Employee.find_or_initialize_with_error_by(:confirmation_token, @confirmation_token)
    @requires_password = true
    self.resource = @confirmable
    render 'devise/confirmations/show' #Change this if you don't have the views on default path
  end

  def do_confirm
    @confirmable.confirm
    set_flash_message :notice, :confirmed
    sign_in_and_redirect(resource_name, @confirmable)
  end
end

app/controllers/employees/omniauth_callbacks_controller.rb
class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/registrations_controller.rb
class Employees::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees/sessions_controller.rb
class Employees::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employees/unlocks_controller.rb
class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	# find out current employee
	before_action :find_employee

	# Authorize employee
	# @raise [CanCan::AccessDenied] if the user does not have permission
	load_and_authorize_resource :employee

	#
	# This method is root path of application. This method checks whether current_employee is admin or  
	#   he is just a regular employee. If designation of current_employee is admin then he will be 
	#   redirect_to admin_dashbord else he will stay here and booking, complaints object will be set
	# @return redirect to admin_dashbord if he is admin else intialize @booking to all future bookings 
	#    and @complaints to all complaints in his company 
	def entry
		@company =current_employee.company
      	admin_role_id = @company.roles.find_by(designation: "admin").id
		if current_employee.role_id == admin_role_id 
			redirect_to admin_dashbord_path
		end
			@bookings = @employee.bookings.where(:date_of_booking.gte => Date.today)
			@complaints = @employee.complaints
	end

end

app/helpers/admin/employees_helper.rb
#
# Module Admin provides helper methods related to employee functionalities
#
# @author Amrut Jadhav
#
module Admin::EmployeesHelper
	#
	# @deprecated This function is not more used
	# 
	def company_domain
		"@"<<current_employee.company.name<<".com"
	end
	#
	#
	# Function create roles array available in company. This array is used to create select box for selcting role
	#
	#
	# @return [Array<String,Integer>] @roles Array of roles
	# 
	def list_roles
		roles = current_employee.company.roles
		@roles = []
		roles.each do | role |
			if role.designation!="admin"
				@roles << [role.designation, role.id]
			end
		end
	end
	#
	#
	# Function lists employees in company
	#
	#
	# @return [Array<String,Integer>] @roles Array of employees
	# 
	def list_employees
		employees = current_employee.company.employees
		@employees = []
		employees.each do | emp |
			@employees << [emp.name, emp.id]
		end
	end
	#
	# Function provide role name corresponding to role_id		
	#
	# @param [Integer] role_id Role id
	#
	# @return [String] name Designation of employee
	# 
	def role_name role_id
		current_employee.company.roles.find(role_id).designation
	end
	#
	# Function provide role name corresponding to employee_id
	# @param [Integer] employee_id Employee id
	#
	# @return [String] name Name of employee
	# 
	def employee_name employee_id
		current_employee.company.employees.find(employee_id).name
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/admin/employees/_dash.html.erb
<hr>
<% if @bookings.any? %>
<b>Pending Bookings</b>
	<div class="row">
	<div class="col-md-12">
		<div class="col-md-1">
		<strong>Status</strong>
		</div>
		<div class="col-md-1">
		<strong>Comment</strong>
		</div>
	 	<div class="col-md-1">
		<strong>Employee</strong>
		</div>
		<div class="col-md-2">
		<strong>Resource Name</strong>	
		</div>
		<div class="col-md-2">
		<strong>Date</strong>	
		</div>
		<div class="col-md-1">
		<strong>Time</strong>	
		</div>
		<div class="col-md-1">
		<%= label_tag(:status_grant, "Grant") %>
		</div>
		<div class="col-md-1">
		<%= label_tag(:status_reject, "Reject") %>
		</div>
		<div class="col-md-2">
		<strong></strong>	
		</div>
	</div>
	</div>
		
	<% @bookings.each do |booking|%>
	<div class="row">
	<hr>
	<div class="col-md-12">
		<div class="col-md-1">
		<%=status_normalization1(booking.status)%>
		</div>
		<div class="col-md-1">
		<%=booking.comment%>
		</div>
		<div class="col-md-1">
		<%=booking.employee.name%>
		</div>
		<div class="col-md-2">
		<%=resource_name(booking.resource_id)%>
		</div>
		<div class="col-md-2">
		<%=booking.date_of_booking%>
		</div>
		<div class="col-md-1">
		<%=show_slot_time(booking.resource_id,booking.slot)%>
		</div>
		<%= form_for:status, url:admin_change_status_path do | f |%>
			<div class="col-md-1">
			<%= f.hidden_field :booking_id,value: booking.id%>
			<%= f.submit "Grant",class: 'btn btn-success'%>
			</div>
			<div class="col-md-1">
			<%= f.submit "Reject",class: "btn btn-danger"%>
			</div>
			<div class="col-md-2">
			</div>
			<% end %>

			
	</div>	
	</div>	
	<% end %>
<% else %>
	<h2>No any pending bookings</h2>
<% end %>
<br>
<br>
<br>
<br>
<hr>
<% if @complaints.any? %>
	<b>Pending Complaints</b>
	<div class="col-md-12">
		<div class="col-md-2">
		<strong>Status</strong>
		</div>
		<div class="col-md-2">
		<strong>Comment</strong>
		</div>
		<div class="col-md-2">
		<strong>Resource Name</strong>
		</div>
		<div class="col-md-1">
		<strong>Employee</strong>
		</div>
		<div class="col-md-1">
		<%= label_tag(:status_solve, "Solve") %>
		</div>
		<div class="col-md-4">

		</div>

	</div>


		
	<% @complaints.each do | complaint |%>
	<div class="row">
	<hr>
	<div class="col-md-12">

		<div class="col-md-2">
		<%=status_normalization(complaint.status)%>
		</div>
		<div class="col-md-2	">
		<%=complaint.comment%>
		</div>
		<div class="col-md-2">
		<%=resource_name(complaint.resource_id)%>
		</div>
		<div class="col-md-1">
		<%=complaint.employee.name%>
		</div>
	<%= form_for:status_complaint, url:admin_change_status_path do | f |%>
		<div class="col-md-1">
		<%= f.submit "Solve",class: 'btn btn-success'%>
		<%= f.hidden_field :complaint_id,value: complaint.id%>
		</div>
		<div class="col-md-2">
		
		</div>
		<% end %>
		
		<div class="col-md-2">
			
		</div>

	</div>
	</div>
	<% end %>

<% else %>
<h2>No any pending complaints. Relax...!</h2>

<% end %>
<br>
<br>

app/views/admin/employees/_employee.html.erb
<b>Employees</b>
<div class="row">
	<hr>
	<div class="col-md-14">
		<div class="col-md-2">
		<strong>Name</strong>
		</div>
		<div class="col-md-2">
		<strong>Email</strong>
		</div>
		<div class="col-md-2">
		<strong>Date of Joining</strong>
		</div>
		<div class="col-md-1">
		<strong>Role</strong>
		</div>
		<div class="col-md-1">
		<strong>Manager</strong>
		</div>
		<div class="col-md-2">
		<strong>Edit Link</strong>
		</div>
		<div class="col-md-2">
		</div>
	</div>
</div>

<ul class="list-group">
<% @employees.collect do |employee|%>
<li class="list-group-item">
<div class="row">
	<div class="col-md-14">
		<div class="col-md-2">
			<%=employee.name%>
		</div>
		<div class="col-md-2">
			<%=employee.email%>
		</div>
		<div class="col-md-2">
			<%=employee.date_of_joining%>
		</div>
		<div class="col-md-1">
			<%=role_name(employee.role_id)%>
		</div>
		<div class="col-md-1">
			<%=employee.manager.name%>
		</div>
		<% if employee.id!=current_employee.id %>
		<div class="col-md-1">
			<%= button_to "Edit ", edit_admin_employee_path(employee),:class => "btn btn-info", :method => "get" %>
		</div>
			<div class="col-md-1">
				<%= button_to "Delete ", admin_employee_path(employee), :method => "delete",:class => "btn btn-danger", data: {confirm: "Are you sure?"}  %>
			</div>
		<% end %>
	</div>
</div>
</li>
<% end %>
</ul>

app/views/admin/employees/_error.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
	<% if @employee.errors.any? %>
	<div id="error_explanation">
	<div class="alert alert-danger">
	The form contains <%= pluralize(@employee.errors.count, "error") %>.
	</div>
	<ul>
	<% @employee.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
	</ul>
	</div>
	<% end %>
</div>
</div>

app/views/admin/employees/_form.html.erb
<%= render "error" %>


<%list_roles%>
<% if !@roles.empty?%>
	<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for ['admin', @employee] do | f |%>
			<%=f.label :Name%>
			<%=f.text_field :name , class: "form-control", required: true%>
			<%=f.label :Email%>
	  			<%=f.text_field :email , class: "form-control",required: true%>
			<br>
			<div class="col-md-12">
			<div class="col-md-6">
				<%list_employees%>		
				<%=f.label :Manager%>
				<%= f.select(:manager_id) do %>
					  <% @employees.each do |c| %>
					    <%= content_tag(:option, c.first, value: c.last) %>
					  <% end %>
				<% end %>
			</div>
			<div class="col-md-6">
				<%=f.label :RoleId%>
				<%= f.select(:role_id) do %>
				  <% @roles.each do |c| %>
				    <%= content_tag(:option, c.first, value: c.last) %>
				  <% end %>
				<% end %>
			</div>
			</div>
			<div class="col-md-12">
				
			<div class="col-md-6">
				<%=f.label :Age%>
				<%=f.text_field :age , class: "form-control",required: true%>	
				
			</div>
			<div class="col-md-6">
				<%=f.label "Date Of Joining" %>
				<%=f.date_field :date_of_joining ,required: true%>
			</div>

			</div>
			
				<%= f.submit 'Save Employee', class: "btn btn-primary btn-default"%>
			
		<% end %>
	</div>
	</div>
<% else %>
	<h4>There are currently no roles in company</h4>
	<div class="col-md-2">
	<%= button_to "Add Roles", new_admin_role_path ,:class => "btn btn-info", :method => "get" %>
	</div>
<% end %>

app/views/admin/employees/dashbord.html.erb
<% if @company.resources.any? %>
<%= render "dash" %>
<% else %>
<h4 align="center">There are no resources in your company</h4>
<% end %>

app/views/admin/employees/index.html.erb
<% if @company.employees.any? %>
<%= render "employee" %>
<% else %>
<h2 align="center">No employees are available in your company.</h2>
<% end %>

app/views/admin/employees/show.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>
<div class="col-md-12">
	<div class="col-md-4">
		<strong>Name</strong>
		</div>
		</div>
<div class="col-md-12">
	<div class="col-md-4">
		<%= @employee.name%>
	</div>
</div>
</body>