config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'resource_time_slot/:name' , to: 'bookings#resource_time_slot', as: :timeslots
  get 'booking_date_slots/:resource/date_of_booking=:date_of_booking', to: 'bookings#booking_date_slots', as: :date_slots
  namespace :admin do 
    get 'dashbord' => 'employees#dashbord'
    post 'change_status' => 'employees#change_status'
    resources :employees,:resources, :roles
  end
  resources :bookings, :employees, :complaints, :company
  devise_for :employees, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }, controllers: {
        confirmations: 'employees/confirmations'
      }

      as :employee do
      patch '/employee/confirmation' => 'employees/confirmations#update', :via => :patch, :as => :update_employee_confirmation
  end
  root "employees#entry"
  

end

app/views/admin/resources/_error.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<% if @resource.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@resource.errors.count, "error") %>.
</div>
<ul>
<% @resource.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

</div>
</div>

app/views/admin/resources/_form.html.erb
<%= render "error" %>

<div class="row">
 	<div class="col-md-3 col-md-offset-4" >
	<%= form_for ["admin",@resource] do | f |%>
		<%=f.label :Name%></td>
		<%=f.text_field :name , required: true, class: "form-control"%>
		<%=f.label :Timeslot%>
		<%=f.time_field :time_slot , required: true%>
	<%= f.submit 'Save Resource',class: "btn btn-success" %>
	<% end %>
</div>
</div>

app/views/admin/resources/_resources.html.erb
<div class="row">
<hr>
<div class="col-md-12">
	<div class="col-md-4">
	<strong>Name</strong>
	</div>
	<div class="col-md-2">
	<strong>TimeSlot</strong>
	</div>
	<div class="col-md-1">
	<strong>Update</strong>
	</div>
	<div class="col-md-1">
	<strong>Delete</strong>
	</div>
	<div class="col-md-4">
	</div>
</div>
</div>
<hr>
<ul class="list-group">
<div class="col-md-12">
<% @resources.each do |resource|%>
<li class="list-group-item">
<div class="row">
	<div class="col-md-4">
	<%= resource.name%></td>
	</div>
	<div class="col-md-2">
	<%= humanize resource %>
	</div>
	<div class="col-md-1">
	<%= button_to "Update", edit_admin_resource_path(resource), :method => "get",:class => "btn btn-info" %>
	</div>
	<div class="col-md-1">
	<%= button_to "Delete", admin_resource_path(resource),method:"delete",:class => "btn btn-danger", data: {confirm: "Are you sure?"}  %>
	</div>
	<div class="col-md-4">
	</div>
	<br><hr>
</div>
</li>
<% end %>
</div>
</ul>

app/views/admin/resources/edit.html.erb
<%= render "form" %>
<%= link_to "Home", admin_employees_path %>

app/views/admin/resources/index.html.erb
<% if @company.resources.any? %>
<%= render "resources" %>
<% else %>
<h2>No resources are available in your company.</h2>
<% end %>

app/views/admin/resources/new.html.erb
<%= render "form" %>

app/views/admin/resources/show.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="col-md-12">
	<div class="col-md-4">
	<strong>Name</strong>
	</div>
	<div class="col-md-4">
	<strong>Alloted Time Slot</strong>
	</div>
</div>
<div class="col-md-12">
	<div class="col-md-4">
	<%= @resource.name%></td>
	</div>
	<div class="col-md-4">
	<%= humanize @resource%>
	</div>
</div>

</body>