config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'resource_time_slot/:name' , to: 'bookings#resource_time_slot', as: :timeslots
  get 'booking_date_slots/:resource/date_of_booking=:date_of_booking', to: 'bookings#booking_date_slots', as: :date_slots
  namespace :admin do 
    get 'dashbord' => 'employees#dashbord'
    post 'change_status' => 'employees#change_status'
    resources :employees,:resources, :roles
  end
  resources :bookings, :employees, :complaints, :company
  devise_for :employees, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }, controllers: {
        confirmations: 'employees/confirmations'
      }

      as :employee do
      patch '/employee/confirmation' => 'employees/confirmations#update', :via => :patch, :as => :update_employee_confirmation
  end
  root "employees#entry"
  

end

app/models/role.rb
#
# Class Role provides functionality to handle roles related to company
#
# @author Amrut Jadhav
#
class Role
	include Mongoid::Document
	include Mongoid::Timestamps
	# @!attribute [rw] skip_validation
	#   @return [Boolean] Whether to skip validation or not
	
	 field :designation, type: String
	 field :priority, type: Integer
	 field :company_id, type: BSON::ObjectId
	 field :department, type: String  
	attr_accessor :skip_validation
	# Associations
	belongs_to :company
	has_many :employees

	# Validations
	validates :designation, :department, :priority, presence: true
	validates :priority, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 2147483647 }, unless: :skip_validation

	validates :designation, uniqueness:{scope: [:company_id,:department], message: "Designation in department should be unique"}
	validates :priority, uniqueness:{scope: :company_id, message: "Priority should be uniq across the company"}
	# Custom validation
	validate :is_name_admin?, :is_none_fields, unless: :skip_validation

	# Callbacks
	before_validation :lower_fields
	after_destroy :add_default_role #unless :company_destruction
	
	private 

	#
	# Check whether user tries to add none role to company
	#
	#
	# @return [void] Add errors to self if role is none
	# 
	def is_none_fields
		unless self.designation!="none" && self.department!="none"
			self.errors[:none] << "=> You can't create none role"
		end
	end

	#
	# When a particular role is deleted then make roles of associated employee as none
	#
	#
	# @return [void] Update the associated employees role as default
	# 
	def add_default_role 
		empty_role_id = self.company.roles.find_by(designation:"none").id
		if self.employees.any? 
			self.employees.each do |x| 
				x.skip_password_validation = true
				x.update(role_id: empty_role_id)
			end
		end
	end

	#
	# Check whether user trying to add admin role to company
	#
	#
	# @return [void] Add error to self if role is admin
	# 
	def is_name_admin?
		unless self.designation != 'admin' 
			self.errors[:admin_designation] << "=> You can't assign the admin designation to another employees"
		end
	end

	#
	# Downcase the department and designation field of role
	#
	#
	# @return [void] Downcase the fields
	# 
	def lower_fields
		if self.designation and self.department
			self.designation.downcase!
			self.department.downcase!
		end
	end

end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
	before_action :find_company
	before_action :find_role, only: [:edit, :show]

  load_and_authorize_resource :role
  def index
    @roles = @company.roles
  end

  def new
  	@role = @company.roles.new
  end

  def create
    @role =  @company.roles.build(role_params)
  	if @role.save
      flash[:success] = "Role has successfully created"
  		redirect_to admin_roles_path
  	else
  		render :new
  	end
  end

  def show
    redirect_to admin_roles_path
  end

  def edit;   end

  def update 
    if @role.update_attributes(role_params)
      flash[:success] = "Role has succefully updated"
      redirect_to admin_roles_path
    else
      render :edit
    end
  end

  def destroy; 
    if @role.destroy
      flash[:success] = "Role has been succefully deleted"
    else
      flash[:error] = "Error while deleting role"
    end
    redirect_to admin_roles_path
  end


  private

  def role_params
  	params.require(:role).permit(:designation,:department,:priority)
  end

  def find_role
    # find_company
  	@role = @company.roles.find(params[:id])
  end

end

app/helpers/admin/roles_helper.rb
#
# Module Admin provides helper methods for role
#
# @author Amrut Jadhav amrut@amuratech.com
#
module Admin::RolesHelper
end

app/views/admin/roles/_error.html.erb
<div class="row">
<div class="col-md-12 ">
<% if @role.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@role.errors.count, "error") %>.
</div>
<ul>
<% @role.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
</div>
</div>

app/views/admin/roles/_priority.html.erb
<div class="col-md-6">
	

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Priority</th>
      <th>Designation</th>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
  <%	Role.where(company_id:current_employee.company.id).sort_by(&:priority).each do |x| %>
    <tr>
      
      <td><%= x.priority %></td>
      <td><%= x.designation %></td>
      <td><%= x.department %></td>
    </tr>
  <% end %>
 </tbody>
 </table>

</div>

app/views/admin/roles/_roles.html.erb
<div class="row">
<hr>
<div class="col-md-12 col-md-offset-3" align="center">
	<div class="col-md-2">
	<strong>Priority</strong>
	</div>
	<div class="col-md-2">
	<strong>Name</strong>
	</div>
	<div class="col-md-2">
	<strong>Department</strong>
	</div>
	
</div>
</div>

<ul class="list-group">
<% @roles.sort_by(&:priority).each do |role|%>
<li class="list-group-item">
<div class="row" align="center">
<div class="col-md-12 col-md-offset-3">
	
	<div class="col-md-2">
		<%= role.priority%>
	</div>
	<div class="col-md-2">
		<%= role.designation%>
	</div>
	<div class="col-md-2">
		<%= role.department%>
	</div>
	<% if role.priority!=0 && role.priority!=1 %>
		<div class="col-md-1">
			<%= button_to "Edit",edit_admin_role_path(role), method: "get", class: "btn btn-success" %>
		</div>

		<div class="col-md-1">
			<%= button_to "Delete", admin_role_path(role),method: "delete", class: "btn btn-danger", data: {confirm: "Are you sure?"} %>
		</div>
	<% end %>
</div>
</div>
</li>
<% end %>
</ul>

app/views/admin/roles/edit.html.erb
<div class="row">
<div class="col-md-12">
	
<div class="col-md-6">
<%= render "error" %>
</div>
</div>
<div class="row">
<div class="col-md-6">
		<%= form_for ['admin', @role] do | f |%>
		<%=f.label :Designation%>
		<%=f.text_field :designation , class: "form-control", required: true, placeholder: "Designation of Employee"%>
		<%=f.label :Department%>
		<%=f.text_field :department , class: "form-control", required: true, placeholder: "Department of Employee"%>
		<%=f.label :Priority%>
		<%=f.text_field :priority , class: "form-control", required: true, placeholder: "Priority of Employee in Company"%>
		<%= f.submit 'Edit Role', class: "btn btn-primary btn-default"%>
<% end %>
</div>
<%= render "priority" %>
</div>

</div>

app/views/admin/roles/index.html.erb
<% if @company.roles.any? %>
<%= render "roles" %>
<% else %>
<h2 align="center">No roles are available in your company.</h2>
<% end %>

app/views/admin/roles/new.html.erb
<div class="row">
<div class="col-md-12">
	
<%= render "error" %>
</div>
<div class="row">
<div class="col-md-6">
		<%= form_for ['admin', @role] do | f |%>
		<%=f.label :Designation%>
		<%=f.text_field :designation , class: "form-control", required: true, placeholder: "Designation of Employee"%>
		<%=f.label :Department%>
		<%=f.text_field :department , class: "form-control", required: true, placeholder: "Department of Employee"%>
		<%=f.label :Priority%>
		<!-- <input type="text" id="phone" name="phone" onkeypress="phoneno()" maxlength="10"> -->
		<%=f.text_field :priority , class: "form-control", id:"prio", required: true, placeholder: "Priority of Employee in Company",onkeypress: "check()", maxlength: "10"%>
		<%= f.submit 'Create Role', class: "btn btn-primary btn-default"%>
<% end %>
</div>
<%= render "priority" %>
</div>

</div>


<script>        
           function check(){          
            $('prio').keypress(function(e) {
                var a = [];
                var k = e.which;

                for (i = 48; i < 58; i++)
                    a.push(i);

                if (!(a.indexOf(k)>=0))
                    e.preventDefault();
            });
        }
       </script>

app/views/admin/roles/show.html.erb
<div class="row">
	<div class="col-md-3 col-md-offset-3">

		<h3>Designation:<%= @role.designation %><h3> 
		
		 <h3>Department:<%= @role.department %></h3>
		
		<h3>Priority:<%= @role.priority %></h3>
		
	</div>
</div>