config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'resource_time_slot/:name' , to: 'bookings#resource_time_slot', as: :timeslots
  get 'booking_date_slots/:resource/date_of_booking=:date_of_booking', to: 'bookings#booking_date_slots', as: :date_slots
  namespace :admin do 
    get 'dashbord' => 'employees#dashbord'
    post 'change_status' => 'employees#change_status'
    resources :employees,:resources, :roles
  end
  resources :bookings, :employees, :complaints, :company
  devise_for :employees, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }, controllers: {
        confirmations: 'employees/confirmations'
      }

      as :employee do
      patch '/employee/confirmation' => 'employees/confirmations#update', :via => :patch, :as => :update_employee_confirmation
  end
  root "employees#entry"
  

end

app/views/layouts/_adminheader.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "Resource Booking", "#", id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", admin_dashbord_path %></li>

<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Company<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "View",company_index_path %></li>
	</ul>
</li>




<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Employee<span class="caret"></span></a>
	<ul class="dropdown-menu">
	<% if can? :create, Employee.new %>
		<li><%= link_to "Add", new_admin_employee_path %></li>
	<% end %>
		<li><%= link_to "View",admin_employees_path %></li>
	</ul>
</li>

<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Resource<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "Add", new_admin_resource_path %></li>
		<li><%= link_to "View", admin_resources_path %></li>
	</ul>
</li>
<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Booking<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "View", bookings_path %></li>
	</ul>
</li>

<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Role<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "Add", new_admin_role_path %></li>
		<li><%= link_to "View", admin_roles_path %></li>
	</ul>
</li>


<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Complaints<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "View", complaints_path %></li>
	</ul>
</li>
<li><%= link_to "Log out", destroy_employee_session_path, method: "delete" , data: {confirm: "Are you sure?"} %></li>

</ul>
</nav>
</div>
</header>

app/views/layouts/_alert.html.erb
<%= yield(:msg) %>

app/views/layouts/_employeeheader.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "Resource Booking", root_path, id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", root_path %></li>

<% if employee_signed_in? %>

<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Booking<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "View", bookings_path %></li>
		<li><%= link_to "Add", new_booking_path %></li>
	</ul>
</li>

<li class="dropdown">
	<a  class="dropdown-toggle" data-toggle="dropdown" href="#">Complaints<span class="caret"></span></a>
	<ul class="dropdown-menu">
		<li><%= link_to "View", complaints_path %></li>
		<li><%= link_to "Add", new_complaint_path %></li>
	</ul>
</li>

<li><%= link_to "Log out", destroy_employee_session_path, method: "delete", data: {confirm: "Are you sure?"}  %></li>

<% else %>
<li><%= link_to "Log in", root_path %></li>
<% end %>
</ul>
</nav>
</div>
</header>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
  <hr>
    <div class="col-lg-12">
      <div class="col-md-8">
        <a href="#">Terms of Service</a> | <a href="#">Privacy</a>    
      </div>
      <div class="col-md-4">
        <p class="muted pull-right">© 2016 Company Name. All rights reserved</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_layout.html.erb
<%= form_for @resource do | f |%>
<table>
	<tr>
		<td>
			<%=f.label :Name%></td>
		<td>
			<%=f.text_field :name %>
		</td>
	</tr>
	<tr></tr>
	<tr>
		<td>
			<%=f.label :Count%></td>
		<td><%=f.text_field :count %>
		</td>
	</tr>
	<tr></tr>
<tr>
	<td>
	<%= f.submit 'Save Resource'%>
	</td>
</tr>

</table>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">	#If a browser doesn't support the HTML 5, include this
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>

<% if employee_signed_in? %>
<% @company =current_employee.company %>
<% admin_role_id = @company.roles.find_by(designation: "admin").id %>
<%= (current_employee.role_id==admin_role_id )? (render 'layouts/adminheader') :( render   'layouts/employeeheader') %>
<% else %>
<%= render 'layouts/employeeheader' %>
<% end %>
<div class="container">
<% flash.each do |message_type, message| %>
<% if message.include?"[" %>
	<% message.split(",").each do |x| %>
		<div class="alert alert-<%= message_type %>"><%= x %></div>
	<% end %>
<% else %>
	<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<% end %>


<%= yield %>
</div>
</body>
<%= render 'layouts/footer' %>
<div align="center">
<br>
<br>
	<%= debug(params) if Rails.env.development? %>
	<% if employee_signed_in? %>
		<%= current_employee.inspect %>
	<% end %>	
</div>


</html>